// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.example.solar_alarm.services.Alarm`
class Alarm extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Alarm> $type;

  @jni$_.internal
  Alarm.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/solar_alarm/services/Alarm',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Alarm?> nullableType = $Alarm$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Alarm> type = $Alarm$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Alarm(jni$_.JObject context) {
    final _$context = context.reference;
    return Alarm.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_getContext = _class.instanceMethodId(
    r'getContext',
    r'()Landroid/content/Context;',
  );

  static final _getContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final android.content.Context getContext()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getContext() {
    return _getContext(
      reference.pointer,
      _id_getContext as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_setAlarm = _class.instanceMethodId(
    r'setAlarm',
    r'(Ljava/lang/String;ZZZ)V',
  );

  static final _setAlarm =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              int,
            )
          >();

  /// from: `public fun setAlarm(alarmJson: kotlin.String, save: kotlin.Boolean, asExtra: kotlin.Boolean, unique: kotlin.Boolean): kotlin.Unit`
  void setAlarm(jni$_.JString string, bool z, bool z1, bool z2) {
    final _$string = string.reference;
    _setAlarm(
      reference.pointer,
      _id_setAlarm as jni$_.JMethodIDPtr,
      _$string.pointer,
      z ? 1 : 0,
      z1 ? 1 : 0,
      z2 ? 1 : 0,
    ).check();
  }

  static final _id_getNextAlarmTimeForRepeatDays = _class.instanceMethodId(
    r'getNextAlarmTimeForRepeatDays',
    r'(Lorg/json/JSONObject;Z)Ljava/lang/Long;',
  );

  static final _getNextAlarmTimeForRepeatDays =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun getNextAlarmTimeForRepeatDays(alarm: org.json.JSONObject, setToday: kotlin.Boolean): kotlin.Long?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JLong? getNextAlarmTimeForRepeatDays(jni$_.JObject jSONObject, bool z) {
    final _$jSONObject = jSONObject.reference;
    return _getNextAlarmTimeForRepeatDays(
      reference.pointer,
      _id_getNextAlarmTimeForRepeatDays as jni$_.JMethodIDPtr,
      _$jSONObject.pointer,
      z ? 1 : 0,
    ).object<jni$_.JLong?>(const jni$_.$JLong$NullableType$());
  }

  static final _id_getAlarm = _class.instanceMethodId(
    r'getAlarm',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _getAlarm =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun getAlarm(alarmName: kotlin.String): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getAlarm(jni$_.JString string) {
    final _$string = string.reference;
    return _getAlarm(
      reference.pointer,
      _id_getAlarm as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getAllAlarms = _class.instanceMethodId(
    r'getAllAlarms',
    r'()Ljava/util/List;',
  );

  static final _getAllAlarms =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun getAllAlarms(): kotlin.collections.List<kotlin.String>`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<jni$_.JString> getAllAlarms() {
    return _getAllAlarms(
      reference.pointer,
      _id_getAllAlarms as jni$_.JMethodIDPtr,
    ).object<jni$_.JList<jni$_.JString>>(
      const jni$_.$JList$Type$<jni$_.JString>(jni$_.$JString$Type$()),
    );
  }

  static final _id_cancelAlarm = _class.instanceMethodId(
    r'cancelAlarm',
    r'(Ljava/lang/String;)V',
  );

  static final _cancelAlarm =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun cancelAlarm(alarmName: kotlin.String): kotlin.Unit`
  void cancelAlarm(jni$_.JString string) {
    final _$string = string.reference;
    _cancelAlarm(
      reference.pointer,
      _id_cancelAlarm as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).check();
  }

  static final _id_rescheduleAllAlarms = _class.instanceMethodId(
    r'rescheduleAllAlarms',
    r'()V',
  );

  static final _rescheduleAllAlarms =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun rescheduleAllAlarms(): kotlin.Unit`
  void rescheduleAllAlarms() {
    _rescheduleAllAlarms(
      reference.pointer,
      _id_rescheduleAllAlarms as jni$_.JMethodIDPtr,
    ).check();
  }
}

final class $Alarm$NullableType$ extends jni$_.JType<Alarm?> {
  @jni$_.internal
  const $Alarm$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/solar_alarm/services/Alarm;';

  @jni$_.internal
  @core$_.override
  Alarm? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Alarm.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Alarm?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Alarm$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Alarm$NullableType$) &&
        other is $Alarm$NullableType$;
  }
}

final class $Alarm$Type$ extends jni$_.JType<Alarm> {
  @jni$_.internal
  const $Alarm$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/solar_alarm/services/Alarm;';

  @jni$_.internal
  @core$_.override
  Alarm fromReference(jni$_.JReference reference) =>
      Alarm.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Alarm?> get nullableType => const $Alarm$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Alarm$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Alarm$Type$) && other is $Alarm$Type$;
  }
}

/// from: `com.example.solar_alarm.services.Prayer`
class Prayer extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Prayer> $type;

  @jni$_.internal
  Prayer.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/solar_alarm/services/Prayer',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Prayer?> nullableType = $Prayer$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Prayer> type = $Prayer$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Prayer(jni$_.JObject context) {
    final _$context = context.reference;
    return Prayer.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_getContext = _class.instanceMethodId(
    r'getContext',
    r'()Landroid/content/Context;',
  );

  static final _getContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final android.content.Context getContext()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getContext() {
    return _getContext(
      reference.pointer,
      _id_getContext as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_updatePrayerSettings = _class.instanceMethodId(
    r'updatePrayerSettings',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _updatePrayerSettings =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun updatePrayerSettings(name: kotlin.String, status: kotlin.String): kotlin.Unit`
  void updatePrayerSettings(jni$_.JString string, jni$_.JString string1) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    _updatePrayerSettings(
      reference.pointer,
      _id_updatePrayerSettings as jni$_.JMethodIDPtr,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }

  static final _id_getPrayerTimesFromLocation = _class.instanceMethodId(
    r'getPrayerTimesFromLocation',
    r'(Ljava/lang/Double;Ljava/lang/Double;)Ljava/util/Map;',
  );

  static final _getPrayerTimesFromLocation =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun getPrayerTimesFromLocation(latitude: kotlin.Double?, longitude: kotlin.Double?): kotlin.collections.Map<kotlin.String, kotlin.Any>`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JMap<jni$_.JString, jni$_.JObject> getPrayerTimesFromLocation(
    jni$_.JDouble? double,
    jni$_.JDouble? double1,
  ) {
    final _$double = double?.reference ?? jni$_.jNullReference;
    final _$double1 = double1?.reference ?? jni$_.jNullReference;
    return _getPrayerTimesFromLocation(
      reference.pointer,
      _id_getPrayerTimesFromLocation as jni$_.JMethodIDPtr,
      _$double.pointer,
      _$double1.pointer,
    ).object<jni$_.JMap<jni$_.JString, jni$_.JObject>>(
      const jni$_.$JMap$Type$<jni$_.JString, jni$_.JObject>(
        jni$_.$JString$Type$(),
        jni$_.$JObject$Type$(),
      ),
    );
  }

  static final _id_schedulePrayerAlarms = _class.instanceMethodId(
    r'schedulePrayerAlarms',
    r'()V',
  );

  static final _schedulePrayerAlarms =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun schedulePrayerAlarms(): kotlin.Unit`
  void schedulePrayerAlarms() {
    _schedulePrayerAlarms(
      reference.pointer,
      _id_schedulePrayerAlarms as jni$_.JMethodIDPtr,
    ).check();
  }
}

final class $Prayer$NullableType$ extends jni$_.JType<Prayer?> {
  @jni$_.internal
  const $Prayer$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/solar_alarm/services/Prayer;';

  @jni$_.internal
  @core$_.override
  Prayer? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Prayer.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Prayer?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Prayer$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Prayer$NullableType$) &&
        other is $Prayer$NullableType$;
  }
}

final class $Prayer$Type$ extends jni$_.JType<Prayer> {
  @jni$_.internal
  const $Prayer$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/solar_alarm/services/Prayer;';

  @jni$_.internal
  @core$_.override
  Prayer fromReference(jni$_.JReference reference) =>
      Prayer.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Prayer?> get nullableType => const $Prayer$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Prayer$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Prayer$Type$) && other is $Prayer$Type$;
  }
}

/// from: `com.example.solar_alarm.services.Logger`
class Logger extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Logger> $type;

  @jni$_.internal
  Logger.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/solar_alarm/services/Logger',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Logger?> nullableType = $Logger$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Logger> type = $Logger$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Logger(jni$_.JObject context) {
    final _$context = context.reference;
    return Logger.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_getContext = _class.instanceMethodId(
    r'getContext',
    r'()Landroid/content/Context;',
  );

  static final _getContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final android.content.Context getContext()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getContext() {
    return _getContext(
      reference.pointer,
      _id_getContext as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_append = _class.instanceMethodId(
    r'append',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _append =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun append(tag: kotlin.String, message: kotlin.String): kotlin.Unit`
  void append(jni$_.JString string, jni$_.JString string1) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    _append(
      reference.pointer,
      _id_append as jni$_.JMethodIDPtr,
      _$string.pointer,
      _$string1.pointer,
    ).check();
  }

  static final _id_history = _class.instanceMethodId(
    r'history',
    r'()Ljava/util/List;',
  );

  static final _history =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun history(): kotlin.collections.List<kotlin.String>`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<jni$_.JString> history() {
    return _history(
      reference.pointer,
      _id_history as jni$_.JMethodIDPtr,
    ).object<jni$_.JList<jni$_.JString>>(
      const jni$_.$JList$Type$<jni$_.JString>(jni$_.$JString$Type$()),
    );
  }

  static final _id_clear = _class.instanceMethodId(r'clear', r'()V');

  static final _clear =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun clear(): kotlin.Unit`
  void clear() {
    _clear(reference.pointer, _id_clear as jni$_.JMethodIDPtr).check();
  }
}

final class $Logger$NullableType$ extends jni$_.JType<Logger?> {
  @jni$_.internal
  const $Logger$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/solar_alarm/services/Logger;';

  @jni$_.internal
  @core$_.override
  Logger? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Logger.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Logger?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Logger$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Logger$NullableType$) &&
        other is $Logger$NullableType$;
  }
}

final class $Logger$Type$ extends jni$_.JType<Logger> {
  @jni$_.internal
  const $Logger$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/solar_alarm/services/Logger;';

  @jni$_.internal
  @core$_.override
  Logger fromReference(jni$_.JReference reference) =>
      Logger.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Logger?> get nullableType => const $Logger$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Logger$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Logger$Type$) && other is $Logger$Type$;
  }
}
